export const PRODUCTACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_UC: "SET_UC",
  SET_ACCOUNTS: "SET_ACCOUNTS",
  SET_COUPONS: "SET_COUPONS",
  SET_FEEDBACKS: "SET_FEEDBACKS",
  SET_ORDERS: "SET_ORDERS",
  SET_WISH_LIST: "SET_WISH_LIST",
  SET_ORDER_BALANCE : "SET_ORDER_BALANCE",
  SET_USER_ACCOUNTS: "SET_USER_ACCOUNTS",
};
