export const USERACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_USER: "SET_USER",
  SET_ERROR: "SET_ERROR",
  LOGIN_USER: "LOGIN_USER",
  SIGN_UP_USER: "SIGN_UP_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_USERS: "SET_USERS",
};
